name: Build android Android Wheels

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.8'

      - name: install cibuildwheel
        run: pip install cibuildwheel

      - name: setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: build wheels
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          mkdir -p build/wheels
          cd build
          bash ../other_scripts/pips/android.sh

      - run: ls build/wheels

      - uses: actions/upload-artifact@v4
        with:
          name: android-android-wheels
          path: build/wheels/

  anaconda_upload:
    name: Upload to Anaconda
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android-android-wheels
          path: wheels/

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.8'

      - name: install anaconda client
        run: pip install anaconda-client

      - name: publish to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          for FILE in wheels/*; do
            anaconda upload --force "$FILE" \
              --user kivyschool \
              --summary "android Android wheel"
          done
