name: Build kivy2x macOS Wheels

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.8'

      - name: install cibuildwheel
        run: pip install cibuildwheel

      - name: build wheels
        run: |
          mkdir -p build/wheels
          cd build
          bash ../kivy_scripts/kivy2x_build_macos_wheels.sh

      - run: ls build/wheels

      - uses: actions/upload-artifact@v4
        with:
          name: kivy2x-macos-wheels
          path: build/wheels/

  r2_upload:
    name: Upload to R2
    needs: [build]
    uses: ./.github/workflows/r2-upload.yml
    with:
      artifact: kivy2x-macos-wheels
    secrets:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
